[versions]
debugOverlay = "1.1.3"

[libraries]
firebase-analytics = "com.google.firebase:firebase-analytics-ktx:21.0.0"
firebase-crashlytics-ktx = "com.google.firebase:firebase-crashlytics-ktx:18.2.11"
firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.8.0"

changelog = "com.github.gabrielemariotti.changeloglib:changelog:2.1.0"
simularity = "info.debatty:java-string-similarity:2.0.0"
xlog = "com.elvishew:xlog:1.11.0"

debugOverlay-standard = { module = "com.ms-square:debugoverlay", version.ref = "debugOverlay" }
debugOverlay-noop = { module = "com.ms-square:debugoverlay-no-op", version.ref = "debugOverlay" }

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"