[versions]

[libraries]
xlog = "com.elvishew:xlog:1.11.1"

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"
composeRatingbar = "com.github.a914-gowtham:compose-ratingbar:1.3.12"

gradleversionsx = "com.github.ben-manes:gradle-versions-plugin:0.53.0"

sqlcipher = "net.zetetic:sqlcipher-android:4.11.0"

exifinterface = "androidx.exifinterface:exifinterface:1.4.1"

google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev20251019-2.0.0"

zxing-android-embedded = "com.journeyapps:zxing-android-embedded:4.3.0"
