[versions]

[libraries]
similarity = "info.debatty:java-string-similarity:2.0.0"
xlog = "com.elvishew:xlog:1.11.1"

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"
composeRatingbar = "com.github.a914-gowtham:compose-ratingbar:1.3.12"

gradleversionsx = "com.github.ben-manes:gradle-versions-plugin:0.52.0"

sqlcipher = "net.zetetic:sqlcipher-android:4.6.1"

exifinterface = "androidx.exifinterface:exifinterface:1.4.0"

google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev20250216-2.0.0"