[versions]

[libraries]
firebase-analytics = "com.google.firebase:firebase-analytics:22.0.2"
firebase-crashlytics-ktx = "com.google.firebase:firebase-crashlytics:19.0.3"
firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:3.0.2"

simularity = "info.debatty:java-string-similarity:2.0.0"
xlog = "com.elvishew:xlog:1.11.1"

ratingbar = "me.zhanghai.android.materialratingbar:library:1.4.0"
composeRatingbar = "com.github.a914-gowtham:compose-ratingbar:1.3.12"

versionsx = "com.github.ben-manes:gradle-versions-plugin:0.51.0"

sqlcipher = "net.zetetic:sqlcipher-android:4.6.0"

exifinterface = "androidx.exifinterface:exifinterface:1.3.7"

google-api-services-drive = "com.google.apis:google-api-services-drive:v3-rev20240628-2.0.0"