blank_issues_enabled: false
contact_links:
  - name: âš ï¸ Extension/source issue
    url: https://github.com/komikku-app/komikku-extensions/issues/new/choose
    about: Issues and requests for official extensions and sources should be opened in the extensions repository instead
  - name: ğŸ“¦ Extensions
    url: https://komikku-app.github.io/tachiyomi-extensions/
    about: List of all available extensions with download links
  - name: ğŸ–¥ï¸ Tachiyomi website
    url: https://tachiyomi.org/
    about: Guides, troubleshooting, and answers to common questions
