blank_issues_enabled: false
contact_links:
  - name: âŒ Help with Extensions
    url: https://komikku-app.github.io/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: ğŸ–¥ï¸ Komikku website
    url: https://komikku-app.github.io/
    about: Guides, troubleshooting, and answers to common questions
