name: Remote Dispatch Action Initiator
 
on:
  push:
   branches: 
    - 'preview'
 
jobs:
  trigger_preview_build:
    name: Trigger preview build
    if: ${{ github.ref == 'refs/heads/preview' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Create Tag
        run: |
          git tag "${{ github.run_number }}"
          git push origin "${{ github.run_number }}"

      - name: PING - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/komikku-app/KomikkuPreview/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
