name: Remote Dispatch Preview Build
# Manually send a dispatch to build standard preview (master) or dev preview (other refs)

on:
  # Dispatch or Manual triggers
  workflow_dispatch:

#  push:
#    branches:
#      - master
#      # - develop
#    paths:
#      - '**'
#      - '!**.md'
#      - '!.github/**'
#      - '.github/scripts/**'
#      - '.github/workflows/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  trigger_preview_build:
    name: Trigger preview build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@31ae3562f68c96d481c31bc1a8a55cc1be162f83 # v3.4.1

      - name: Prepare build
        id: prepare_build
        run: |
          set -e

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_OUTPUT

      - name: Create Tag 'r${{ steps.prepare_build.outputs.COMMIT_COUNT }}'
        if: ${{ github.ref }} == "refs/heads/master"
        run: |
          git tag "r${{ steps.prepare_build.outputs.COMMIT_COUNT }}"
          git push origin "r${{ steps.prepare_build.outputs.COMMIT_COUNT }}"

      - name: Get branch names
        id: branch_names
        uses: tj-actions/branch-names@6871f53176ad61624f978536bbf089c574dc19a2 # v8.0.1

      - name: Invoke workflow in preview repo
        uses: benc-uk/workflow-dispatch@25b02cc069be46d637e8fe2f1e8484008e9e9609 # v1.2.3
        with:
          workflow: build_app.yml
          repo: komikku-app/komikku-preview
          ref: "refs/heads/main"
          token: "${{ secrets.BOT_PAT }}"
          inputs: '{ "git-ref": "${{ steps.branch_names.outputs.current_branch }}" }'
