name: Remote Dispatch Action Initiator
 
on:
  push:
   branches: 
    - 'master'
 
jobs:
  trigger_preview_build:
    name: Trigger preview build
    if: ${{ github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: TAG - Bump version and push tag
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          RELEASE_BRANCHES: master
          DEFAULT_BUMP: patch

      - name: PING - Dispatch initiating repository event
        run: |
          curl -X POST https://api.github.com/repos/jobobby04/TachiyomiSYPreview/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACCESS_TOKEN }} \
          --data '{"event_type": "ping", "client_payload": { "repository": "'"$GITHUB_REPOSITORY"'" }}'
